# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CDALocation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CDALocation

  pod 'CDAUtilities', 	:path => '../CDAUtilities'
  pod 'CDANotification', :path => '../CDANotification'

end
